env:
  global:
    - CC_TEST_REPORTER_ID=68ef978c26ab7a78297fd20204ea282dcd11d9ad428d5daa3ca2575c05f257b0

language: node_js

node_js:
  - '10'

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - npm install
  - npm run lint
  #- npm run cover
  #- npm run nyc_init
  - npm audit fix --force
  - npm run test
  - npm run doc

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 9c2b5cae23750edd24afb63a8a4824f605be6de7  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    repo: ucsd-cse112/team6
    branches: 
      only:
        - master
    #all_branches: true
  local_dir: ./docs
  


notifications:
  slack: cse112-sp19-team6:N12LyYY9qQqATj006RyRVmKk
